import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/_ui/Header";
import PageTransistion from "./_ui/PageTransistion";
import StairTransition from "./_ui/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransistion>{children}</PageTransistion>
      </body>
    </html>
  );
}
